export const testIds = {
  auth: {
    loginTitle: 'auth-login-title',
    registerHandle: 'auth-register-handle',
    registerName: 'auth-register-name',
    registerEmail: 'auth-register-email',
    registerPassword: 'auth-register-password',
    registerConfirmPassword: 'auth-register-confirm-password',
    registerPrivacyCheckbox: 'auth-register-privacy-checkbox',
    registerSubmit: 'auth-register-submit',
    loginEmail: 'auth-login-email',
    loginPassword: 'auth-login-password',
  },
  feeds: {
    communityHeading: 'feeds-community-heading',
  },
  posts: {
    newPostButton: 'posts-new-post-button',
    composerContent: 'posts-composer-content',
    composerPublish: 'posts-composer-publish',
    composerPollType: 'posts-composer-poll-type',
    pollOption: (index: number) => `posts-poll-option-${index}`,
    repostButton: 'posts-repost-button',
  },
  groups: {
    createPageTitle: 'groups-create-page-title',
    nameInput: 'groups-name-input',
    handleInput: 'groups-handle-input',
    descriptionInput: 'groups-description-input',
    rulesInput: 'groups-rules-input',
    whoCanPostEventsMembers: 'groups-who-can-post-events-members',
    whoCanPostEventsModerators: 'groups-who-can-post-events-moderators',
    createSubmit: 'groups-create-submit',
    duplicateHandleError: 'groups-duplicate-handle-error',
    headerTitle: 'groups-header-title',
    tabGroup: 'tab-group',
    tabEvents: 'groups-tab-events',
    tabDescription: 'groups-tab-description',
    searchInput: 'groups-search-input',
  },
  events: {
    formBasicDetails: 'events-form-basic-details',
    nameInput: 'events-name-input',
    descriptionInput: 'events-description-input',
    startInput: 'events-start-input',
    createSubmit: 'events-create-submit',
    newEventButton: 'events-new-event-button',
    pageHeading: 'events-page-heading',
  },
  explore: {
    searchInput: 'explore-search-input',
    noProfilesFound: 'explore-no-profiles-found',
  },
  settings: {
    pageHeading: 'settings-page-heading',
    linkPublicProfile: 'settings-link-public-profile',
    linkAccount: 'settings-link-account',
    linkNotifications: 'settings-link-notifications',
    linkTheme: 'settings-link-theme',
    linkBilling: 'settings-link-billing',
    displayNameInput: 'settings-display-name-input',
    handleInput: 'settings-handle-input',
    bioInput: 'settings-bio-input',
    saveButton: 'settings-save-button',
    currentPasswordInput: 'settings-current-password-input',
    emailInput: 'settings-email-input',
    notificationsPreferencesLink: 'settings-notifications-preferences-link',
    pushDevicesLink: 'settings-notifications-push-devices-link',
    billingHeading: 'settings-billing-heading',
  },
  members: {
    searchInput: 'members-search-input',
  },
  admin: {
    configurationHeading: 'admin-configuration-heading',
    newInviteButton: 'admin-new-invite-button',
  },
  jams: {
    pageHeading: 'jams-page-heading',
  },
  conversations: {
    pageHeading: 'conversations-page-heading',
  },
  notifications: {
    pageHeading: 'notifications-page-heading',
  },
  profile: {
    headerTitle: 'profile-header-title',
    followersHeading: 'profile-followers-heading',
    followingHeading: 'profile-following-heading',
    notFoundTitle: 'profile-not-found-title',
  },
} as const;
