packages:
  - "libraries/*"
  - "platform/*"
  - "examples/*"

linkWorkspacePackages: deep

overrides:
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"
  "@tanstack/react-query": "5.90.16"
  react: "19.2.6"
  react-dom: "19.2.6"
  zod: "^4.3.6"

allowBuilds:
  "@evilmartians/lefthook": true
  "@firebase/util": true
  "@sentry/cli": true
  bcrypt: true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  hyochan-welcome: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  web-audio-api: true

minimumReleaseAgeExclude:
  - livekit-client@2.19.2
  - '@riddl/core@0.2.4'
