// Generated by ts-to-zod
import { z } from 'zod';

import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
extendZodWithOpenApi(z);

export const emojiSchema = z.object({
  category: z.string(),
  shortcode: z.string(),
  static_url: z.string(),
  url: z.string(),
  visible_in_picker: z.boolean(),
});

export const announcementAccountSchema = z.object({
  acct: z.string(),
  id: z.string(),
  url: z.string(),
  handle: z.string(),
});

export const reactionSchema = z.object({
  count: z.number(),
  me: z.boolean().optional(),
  name: z.string(),
  static_url: z.string().optional(),
  url: z.string().optional(),
});

export const announcementStatusSchema = z.object({
  id: z.string(),
  url: z.string(),
});

export const applicationSchema = z.object({
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
  name: z.string(),
  vapid_key: z.string().optional(),
  website: z.string().optional().nullable(),
});

const baseCardSchema = z.object({
  description: z.string(),
  title: z.string(),
  type: z.string(),
  url: z.string(),
});

export const linkCardSchema = baseCardSchema.extend({
  type: z.literal('link'),
});

export const photoCardSchema = baseCardSchema.extend({
  author_name: z.string(),
  author_url: z.string(),
  blurhash: z.string(),
  embed_url: z.string(),
  height: z.number(),
  image: z.string().optional(),
  provider_name: z.string(),
  provider_url: z.string(),
  type: z.literal('photo'),
  width: z.number(),
});

export const iframeCardSchema = baseCardSchema.extend({
  type: z.literal('rich'),
});

export const videoCardSchema = baseCardSchema.extend({
  author_name: z.string(),
  author_url: z.string(),
  blurhash: z.string().optional(),
  height: z.number(),
  html: z.string(),
  image: z.string().optional(),
  provider_name: z.string(),
  provider_url: z.string(),
  type: z.literal('video'),
  width: z.number(),
});

export const listReplyPolicySchema = z.union([
  z.literal('followed'),
  z.literal('list'),
  z.literal('none'),
]);

export const listAccountsDeleteSchema = z.object({
  account_ids: z.array(z.string()),
});

export const listAccountsPostSchema = z.object({
  account_ids: z.array(z.string()),
});

export const listPostSchema = z.object({
  id: z.string().optional(),
  replies_policy: z.string().optional(),
  title: z.string(),
});

export const audioAttachmentMetaOriginalSchema = z.object({
  bitrate: z.number(),
  duration: z.number(),
});

export const gIFVAttachmentMetaOriginalSchema = z.object({
  bitrate: z.number(),
  duration: z.number(),
  frame_rate: z.string(),
  height: z.number(),
  width: z.number(),
});

export const gIFVAttachmentMetaSmallSchema = z.object({
  aspect: z.number(),
  height: z.number(),
  size: z.string(),
  width: z.number(),
});

export const imageAttachmentMetaFocusSchema = z.object({
  x: z.number(),
  y: z.number(),
});

export const imageAttachmentMetaOriginalSchema = z.object({
  aspect: z.number(),
  height: z.number(),
  size: z.string(),
  width: z.number(),
});

export const imageAttachmentMetaSmallSchema = z.object({
  aspect: z.number(),
  height: z.number(),
  size: z.string(),
  width: z.number(),
});

export const unknownAttachmentSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.string(),
  meta: z.record(z.record(z.union([z.number(), z.string()]))),
  preview_url: z.string(),
  remote_url: z.string().optional().nullable(),
  text_url: z.string().optional().nullable(),
  type: z.literal('unknown'),
  url: z.string().nullable(),
});

export const videoAttachmentMetaOriginalSchema = z.object({
  bitrate: z.number(),
  duration: z.number(),
  frame_rate: z.string(),
  height: z.number(),
  width: z.number(),
});

export const videoAttachmentMetaSmallSchema = z.object({
  aspect: z.number(),
  height: z.number(),
  size: z.string(),
  width: z.number(),
});

export const notificationTypeSchema = z.union([
  z.literal('mention'),
  z.literal('status'),
  z.literal('reblog'),
  z.literal('follow'),
  z.literal('follow_request'),
  z.literal('favourite'),
  z.literal('poll'),
  z.literal('update'),
  z.literal('admin.sign_up'),
  z.literal('admin.report'),
]);

export const pollOptionSchema = z.object({
  title: z.string(),
  votes_count: z.number().optional().nullable(),
});

export const pollVotePostSchema = z.object({
  choices: z.array(z.number()),
});

export const searchSchema = z.object({
  account_id: z.string().optional(),
  exclude_unreviewed: z.boolean().optional(),
  following: z.boolean().optional(),
  max_id: z.string().optional(),
  min_id: z.string().optional(),
  q: z.string(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  resolve: z.boolean().optional(),
  type: z.string().optional(),
});

export const statusVisibilitySchema = z.union([
  z.literal('direct'),
  z.literal('private'),
  z.literal('public'),
  z.literal('unlisted'),
  z.literal('local'),
]);

export const statusMentionSchema = z.object({
  acct: z.string(),
  id: z.string(),
  handle: z.string(),
  url: z.string(),
});

export const textStatusPostPollSchema = z.object({
  expires_in: z.number(),
  hide_totals: z.boolean().optional(),
  multiple: z.boolean().optional(),
  options: z.array(z.string()),
});

export const streamEventTypeSchema = z.union([
  z.literal('announcement'),
  z.literal('announcement.delete'),
  z.literal('announcement.reaction'),
  z.literal('conversation'),
  z.literal('delete'),
  z.literal('encrypted_message'),
  z.literal('filters_changed'),
  z.literal('notification'),
  z.literal('status.update'),
  z.literal('update'),
]);

export const streamTypeSchema = z.union([
  z.literal('direct'),
  z.literal('hashtag'),
  z.literal('hashtag:local'),
  z.literal('list'),
  z.literal('public'),
  z.literal('public:local'),
  z.literal('public:local:media'),
  z.literal('public:media'),
  z.literal('public:remote'),
  z.literal('public:remote:media'),
  z.literal('account'),
  z.literal('account:notification'),
]);

export const streamParamsSchema = z.object({
  list: z.string().optional(),
  tag: z.string().optional(),
});

export const tagStatisticSchema = z.object({
  accounts: z.number(),
  day: z.number(),
  following: z.boolean().optional(),
  uses: z.number(),
});

const baseAccountSchema = z.object({
  acct: z.string(),
  avatar: z.string(),
  avatar_static: z.string(),
  bot: z.boolean(),
  created_at: z.string(),
  discoverable: z.boolean().optional(),
  display_name: z.string(),
  emojis: z.array(emojiSchema),
  fields: z.array(z.unknown()),
  followers_count: z.number(),
  following_count: z.number(),
  group: z.boolean(),
  header: z.string(),
  header_static: z.string(),
  id: z.string(),
  last_status_at: z.string().optional(),
  limited: z.boolean().optional(),
  locked: z.boolean(),
  noindex: z.boolean().optional(),
  note: z.string(),
  statuses_count: z.number(),
  suspended: z.boolean().optional(),
  url: z.string(),
  handle: z.string(),
});

export const accountSchema = baseAccountSchema.extend({
  moved: baseAccountSchema,
});

export const tagSchema = z.object({
  history: z.array(tagStatisticSchema).optional(),
  name: z.string(),
  url: z.string(),
});

export const cardSchema = z.union([
  linkCardSchema,
  photoCardSchema,
  iframeCardSchema,
  videoCardSchema,
]);

export const listSchema = z.object({
  id: z.string(),
  replies_policy: listReplyPolicySchema.optional(),
  title: z.string(),
});

export const listAccountsSchema = z.array(accountSchema);

export const audioAttachmentMetaSchema = z.object({
  audio_bitrate: z.string(),
  audio_channels: z.string(),
  audio_encode: z.string(),
  duration: z.number(),
  length: z.string(),
  original: audioAttachmentMetaOriginalSchema,
});

export const gIFVAttachmentMetaSchema = z.object({
  aspect: z.number(),
  duration: z.number(),
  fps: z.number(),
  height: z.number(),
  length: z.string(),
  original: gIFVAttachmentMetaOriginalSchema,
  size: z.string(),
  small: gIFVAttachmentMetaSmallSchema,
  width: z.number(),
});

export const imageAttachmentMetaSchema = z.object({
  focus: imageAttachmentMetaFocusSchema.optional(),
  original: imageAttachmentMetaOriginalSchema,
  small: imageAttachmentMetaSmallSchema,
});

export const videoAttachmentMetaSchema = z.object({
  aspect: z.number().optional(),
  audio_bitrate: z.string().optional(),
  audio_channels: z.string().optional(),
  audio_encode: z.string().optional(),
  duration: z.number().optional(),
  fps: z.number().optional(),
  height: z.number().optional(),
  length: z.string().optional(),
  original: videoAttachmentMetaOriginalSchema,
  size: z.string().optional(),
  small: videoAttachmentMetaSmallSchema,
  width: z.number().optional(),
});

export const pollSchema = z.object({
  emojis: z.array(emojiSchema),
  expired: z.boolean(),
  expires_at: z.string().optional().nullable(),
  id: z.string(),
  multiple: z.boolean().optional(),
  options: z.array(pollOptionSchema),
  own_votes: z.array(z.number()).optional(),
  voted: z.boolean().optional(),
  voters_count: z.number().optional().nullable(),
  votes_count: z.number(),
});

export const mediaStatusPostSchema = z.object({
  id: z.string().optional(),
  in_reply_to_id: z.string().optional(),
  media_ids: z.array(z.string()),
  poll: z.undefined().optional(),
  scheduled_at: z.date().optional(),
  sensitive: z.boolean().optional(),
  spoiler_text: z.string().optional(),
  status: z.string().optional(),
  visibility: statusVisibilitySchema.optional(),
});

export const textStatusPostSchema = z.object({
  id: z.string().optional(),
  in_reply_to_id: z.string().optional(),
  media_ids: z.undefined().optional(),
  poll: textStatusPostPollSchema.optional(),
  scheduled_at: z.date().optional(),
  sensitive: z.boolean().optional(),
  spoiler_text: z.string().optional(),
  status: z.string(),
  visibility: statusVisibilitySchema.optional(),
});

export const announcementSchema = z.object({
  all_day: z.boolean(),
  content: z.string(),
  emojis: z.array(emojiSchema),
  ends_at: z.string().optional().nullable(),
  id: z.string(),
  mentions: z.array(announcementAccountSchema),
  published: z.boolean().optional(),
  published_at: z.string().optional().nullable(),
  read: z.boolean().optional(),
  reactions: z.array(reactionSchema),
  starts_at: z.string().optional().nullable(),
  statuses: z.array(announcementStatusSchema),
  tags: z.array(tagSchema),
  updated_at: z.string().optional().nullable(),
});

export const audioAttachmentSchema = z.object({
  blurhash: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string(),
  meta: audioAttachmentMetaSchema,
  preview_url: z.string(),
  remote_url: z.string().optional().nullable(),
  text_url: z.string().optional().nullable(),
  type: z.literal('audio'),
  url: z.string(),
});

export const gIFVAttachmentSchema = z.object({
  blurhash: z.string(),
  description: z.string().optional().nullable(),
  id: z.string(),
  meta: gIFVAttachmentMetaSchema,
  preview_url: z.string(),
  remote_url: z.string().optional().nullable(),
  text_url: z.string().optional().nullable(),
  type: z.literal('gifv'),
  url: z.string(),
});

export const imageAttachmentSchema = z.object({
  blurhash: z.string(),
  description: z.string().optional().nullable(),
  id: z.string(),
  meta: imageAttachmentMetaSchema,
  preview_remote_url: z.string().optional().nullable(),
  preview_url: z.string(),
  remote_url: z.string().optional().nullable(),
  text_url: z.string().optional().nullable(),
  type: z.literal('image'),
  url: z.string(),
});

export const videoAttachmentSchema = z.object({
  blurhash: z.string(),
  description: z.string().optional().nullable(),
  id: z.string(),
  meta: videoAttachmentMetaSchema,
  preview_url: z.string(),
  remote_url: z.string().optional().nullable(),
  text_url: z.string().optional().nullable(),
  type: z.literal('video'),
  url: z.string().nullable(),
});

export const statusPostSchema = z.union([
  mediaStatusPostSchema,
  textStatusPostSchema,
]);

export const mediaAttachmentSchema = z.union([
  audioAttachmentSchema,
  gIFVAttachmentSchema,
  imageAttachmentSchema,
  unknownAttachmentSchema,
  videoAttachmentSchema,
]);

export const baseStatusSchema = z.object({
  account: accountSchema,
  application: applicationSchema.optional(),
  bookmarked: z.boolean().optional(),
  card: cardSchema.optional().nullable(),
  created_at: z.string(),
  content: z.string(),
  edited_at: z.string().optional(),
  emojis: z.array(emojiSchema),
  favourited: z.boolean().optional(),
  favourites_count: z.number(),
  filtered: z.array(z.unknown()).optional(),
  id: z.string(),
  in_reply_to_account_id: z.string().optional().nullable(),
  in_reply_to_id: z.string().optional().nullable(),
  language: z.string().optional().nullable(),
  media_attachments: z.array(mediaAttachmentSchema),
  mentions: z.array(statusMentionSchema),
  muted: z.boolean().optional(),
  pinned: z.boolean().optional(),
  poll: pollSchema.optional().nullable(),
  reblogged: z.boolean().optional(),
  reblogs_count: z.number(),
  replies_count: z.number(),
  sensitive: z.boolean(),
  spoiler_text: z.string(),
  tags: z.array(tagSchema),
  text: z.string().optional().nullable(),
  uri: z.string(),
  url: z.string().optional().nullable(),
  visibility: statusVisibilitySchema,
});

export const statusSchema = baseStatusSchema.extend({
  reblog: baseStatusSchema.optional().nullable(),
});

export const searchResultsSchema = z.object({
  accounts: z.array(accountSchema),
  hashtags: z.array(tagSchema),
  statuses: z.array(statusSchema),
});

export const statusContextSchema = z.object({
  ancestors: z.array(statusSchema),
  descendants: z.array(statusSchema),
});

export const statusScheduleSchema = z.object({
  id: z.string().optional(),
  media_attachments: z.array(mediaAttachmentSchema),
  params: statusSchema,
  scheduled_at: z.string(),
});

export const notificationSchema = z.object({
  account: accountSchema,
  created_at: z.string(),
  id: z.string(),
  report: z.unknown().optional(),
  type: notificationTypeSchema,
  status: statusSchema.optional(),
});

export const streamPayloadSchema = z.union([notificationSchema, statusSchema]);

export const streamDataSchema = z.object({
  event: streamEventTypeSchema,
  payload: streamPayloadSchema.optional(),
  stream: z.array(streamTypeSchema),
});

export const statusCreateRequestSchema = z
  .object({
    status: z.string().optional(),
    mediaIds: z.array(z.string()).optional(),
    poll: pollSchema.optional(),
    inReplyToId: z.string().optional(),
    sensitive: z.boolean().optional(),
    spoilerText: z.string().optional(),
    visibility: z.enum(['public', 'unlisted', 'private', 'direct']),
    language: z.string().optional(),
    scheduledAt: z
      .string()
      .optional()
      .refine(
        (data) => {
          if (data) {
            const scheduledDate = new Date(data);
            const now = new Date();
            now.setMinutes(now.getMinutes() + 5);
            return scheduledDate > now;
          }
          return true;
        },
        {
          message: 'Scheduled time must be at least 5 minutes in the future',
        },
      ),
  })
  .refine((data) => data.status || data.mediaIds || data.poll, {
    message: 'No content provided',
  })
  .refine((data) => !(data.poll && data.mediaIds), {
    message: 'Polls cannot have media',
  })
  .refine((data) => !(data.poll && !data.poll.expires_at), {
    message: 'Poll expiration is required',
  })
  .refine(
    (data) =>
      !(data.poll && data.poll.options && data.poll.options.length === 0),
    {
      message: 'Poll options are required',
    },
  )
  .refine(
    (data) => !(data.mediaIds && data.status === undefined && !data.poll),
    {
      message: "Text can't be blank",
    },
  );
export type StatusCreateRequest = z.infer<typeof statusCreateRequestSchema>;
