export { Modal } from './Modal';
export { ModalWrapper } from './ModalWrapper';
export type { ModalWrapperProps } from './ModalWrapper';
export { ModalHeader } from './ModalHeader';
export type { ModalHeaderProps } from './ModalHeader';
export { DialogFooter as ModalFooter } from '../ui/dialog';
export type { DialogFooterProps as ModalFooterProps } from '../ui/dialog';
export { getModalManager, useModalManager } from './manager';
export type { ModalManager } from './manager';
export { modalStore } from './store';
export type { ModalControlProps, ModalEntry } from './store';
