server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html html htm;
    }
    default_type text/html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
