import type { accounts } from './accounts';
import type { auth } from './auth';
import type { conversations } from './conversations';
import type { groups } from './groups';
import type { i18n } from './i18n';
import type { jams } from './jams';
import type { location } from './location';
import type { media } from './media';
import type { posts } from './posts';
import type { profiles } from './profiles';
import type { reports } from './reports';
import type { server } from './server';
import type { sso } from './sso';
import type { admin } from './admin';
import type { previewLink } from './previewLink';
import type { search } from './search';
import type { payments } from './payments';
import type { streaming } from './streaming';
import type { WebhookHandler } from '../webhooks';

export type AdminEndpoints = ReturnType<typeof admin>;
export type AccountsEndpoints = ReturnType<typeof accounts>;
export type AuthEndpoints = ReturnType<typeof auth>;
export type ConversationsEndpoints = ReturnType<typeof conversations>;
export type GroupsEndpoints = ReturnType<typeof groups>;
export type I18nEndpoints = ReturnType<typeof i18n>;
export type JamsEndpoints = ReturnType<typeof jams>;
export type LocationEndpoints = ReturnType<typeof location>;
export type MediaEndpoints = ReturnType<typeof media>;
export type PostsEndpoints = ReturnType<typeof posts>;
export type PreviewLinkEndpoints = ReturnType<typeof previewLink>;
export type ProfilesEndpoints = ReturnType<typeof profiles>;
export type ReportsEndpoints = ReturnType<typeof reports>;
export type ServerEndpoints = ReturnType<typeof server>;
export type SsoEndpoints = ReturnType<typeof sso>;
export type SearchEndpoints = ReturnType<typeof search>;
export type PaymentsEndpoints = ReturnType<typeof payments>;
export type StreamingEndpoints = ReturnType<typeof streaming>;

export type Endpoints = {
    admin: AdminEndpoints;
    accounts: AccountsEndpoints;
    auth: AuthEndpoints;
    conversations: ConversationsEndpoints;
    groups: GroupsEndpoints;
    i18n: I18nEndpoints;
    jams: JamsEndpoints;
    location: LocationEndpoints;
    mediaAttachment: MediaEndpoints;
    posts: PostsEndpoints;
    previewLink: PreviewLinkEndpoints;
    profiles: ProfilesEndpoints;
    reports: ReportsEndpoints;
    server: ServerEndpoints;
    sso: SsoEndpoints;
    search: SearchEndpoints;
    payments: PaymentsEndpoints;
    streaming: StreamingEndpoints;
    webhookHandler: WebhookHandler;
}; 